name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # id-token: write and contents: read are required for
      # aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::256777061266:role/gh-actions-role
          aws-region: us-west-2

      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - name: Build
        run: |
          nix build --out-link dist
          tailwindcss \
            -o ./static/css/tailwind.css \
            -i base.css \
            -m
      - name: Terraform Validate
        run: terraform validate -chdir=infra -no-color
      - name: Terraform Apply
        run: terraform apply -chdir=infra -no-color -auto-approve

