name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # id-token: write and contents: read are required for
      # aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::256777061266:role/gh-actions-role
          aws-region: us-west-2

      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - name: Cachix
        uses: cachix/cachix-action@v12
        with:
          name: garrettdavis-dev
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Nix Shell
        uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: .#cicd

      - name: Generate CSS
        run: tailwindcss -o ./static/css/tailwind.css -i base.css -m
      - name: Build
        run: nix build
      - name: Terraform Init
        run: |
          cd infra
          terraform init
      - name: Terraform Validate
        run: |
          cd infra
          terraform validate
      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve

