name: Build Binary

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          tag: v0.14.0
          platform: linux
          arch: x86_64
      - name: Install TailwindCSS
        run: |
          curl -sL -o tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss

      - name: Restore Build Cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: |
            target/**/*

      - name: Build Rust App
        run: |
          cargo lambda build \
            --release \
            --arm64 \
            --lambda-dir lambda \
            --flatten garrettdavis-dev
          du -h lambda/bootstrap
          (
            cd lambda &&
            find . -exec touch -d 1970-01-01T00:00:00 '{}' + &&
            find . -exec zip -q -D -X -9 --compression-method deflate ../dist.zip '{}' +
          )

      - name: Build Static Assets
        run: |
          ./tailwindcss \
            -o dist/tailwindcss.css \
            -i base.css \
            -m

      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Save Build Cache
        id: save-cache
        uses: actions/cache@v3
        with:
          path: |
            tailwindcss
            target/**/*

